---
- name: join to be dc to domain
  hosts: all
  remote_user: "{{remote_user | Administrator}}"
  vars:
    host_name: "{{name}}"
    winadmin: "{{winadmin}}"
    password: "{{password}}"
    primary_dns: 192.168.1.18
    subscription1: ALL
    subscription2: Domain Controllers

  roles:
    - windows_common
    - domain_con
