---
- name: jenkins server
  hosts: all
  remote_user: server
  become: yes
  vars:
    host_name: "{{ name }}"
    subscription1: ALL
    subscription2: jenkins server
    subscription3: linux

  roles:
    - common
    - jenkins 