---
- name: startup basic windows server
  hosts: all
  remote_user: "{{remote_user}}"
  vars:
    host_name: "{{name}}"
    winadmin: "{{winadmin}}"
    password: "{{password}}"
    ou: Staging
    subscription1: ALL
    subscription2: windows
  roles:
    - windows_common
    - join_domain