---
- name: copy ruby service-check
  copy: src=/home/phil/files/sensu-checks/service-check.rb dest=/etc/sensu/plugins/jenkins-check.rb

- name:  run jenkins repo setup script
  script: jenkins.sh

- name: install jenkins
  apt: name=jenkins update_cache=yes
  ignore_errors: yes

- name: run configure shell script
  command: sh /var/lib/dpkg/info/jenkins.postinst configure

- name: echo admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: echo
  #print for admin to see and plug into web interface
- debug: var=echo.stdout_lines
